CREATE TABLE `product_price` (`id` INT NOT NULL AUTO_INCREMENT , 
`product_id` INT NOT NULL , 
`start_date` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP , 
`amount` INT NOT NULL , 
`operator` INT NOT NULL , 
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;